attribute:
    pattern:  /
    defaults: { _controller: "AdminBundle:Attribute:index" }

attribute_show:
    pattern:  /{id}/show
    defaults: { _controller: "AdminBundle:Attribute:show" }

attribute_new:
    pattern:  /new
    defaults: { _controller: "AdminBundle:Attribute:new" }

attribute_create:
    pattern:  /create
    defaults: { _controller: "AdminBundle:Attribute:create" }
    requirements: { _method: post }

attribute_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AdminBundle:Attribute:edit" }

attribute_update:
    pattern:  /{id}/update
    defaults: { _controller: "AdminBundle:Attribute:update" }
    requirements: { _method: post }

attribute_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AdminBundle:Attribute:delete" }
    requirements: { _method: post }
