product:
    pattern: /
    defaults: { _controller: AdminBundle:Product:index }
    
product_create:
    pattern: /create
    defaults: { _controller: AdminBundle:Product:create }

product_show:
    pattern: /show/{id}
    defaults: { _controller: AdminBundle:Product:show }

product_delete:
    pattern: /delete/{id}
    defaults: { _controller: AdminBundle:Product:delete }
    requirements:
        _format: POST
        
product_update:
    pattern: /update/{id}
    defaults: { _controller: AdminBundle:Product:update }
    
product_variant_generate:
    pattern: /variantGenerate/{id}
    defaults: { _controller: AdminBundle:Product:generateVariant }

product_variant_show:
    pattern: /variantShow/{id}
    defaults: { _controller: AdminBundle:Product:variantShow } 
    
product_variant_delete:
    pattern: /variantdelete/{id}
    defaults: { _controller: AdminBundle:Product:variantdelete } 
    
