admin_homepage:
    pattern:  /
    defaults: { _controller: AdminBundle:Default:index }
    
taxonomies:
    prefix: /taxonomies
    resource: "@AdminBundle/Resources/config/routing/taxonomies.yml"
    
shippingcategory:
    resource: "@AdminBundle/Resources/config/routing/shippingcategory.yml"
    prefix:   /shippingcategory

zone:
    resource: "@AdminBundle/Resources/config/routing/zone.yml"
    prefix:   /zone

taxation:
    resource: "@AdminBundle/Resources/config/routing/taxation.yml"
    prefix:   /taxation

taxationrate:
    resource: "@AdminBundle/Resources/config/routing/taxationrate.yml"
    prefix:   /taxationrate
user:
    resource: "@AdminBundle/Resources/config/routing/user.yml"
    prefix:   /user    
adress:
    resource: "@AdminBundle/Resources/config/routing/adress.yml"
    prefix:   /adress

attribute:
    resource: "@AdminBundle/Resources/config/routing/attribute.yml"
    prefix:   /attribute
    
option:
    resource: "@AdminBundle/Resources/config/routing/option.yml"
    prefix:   /option
